# Generated by Django 4.1.4 on 2022-12-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_code_student_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='studgrade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='studname',
        ),
    ]
