# Generated by Django 4.1.4 on 2022-12-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_grade_student_studgrade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studgrade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studname',
            new_name='name',
        ),
    ]
